nameApplication: API Gateway
hostApplication: http://localhost

config:
  port: 3333
  enabledMorgan: true

security:
  enabledJSON: true
  enabledHelmet: true

services:
  - nameRoute: api/v1/user
    url: http://localhost:3000
  - nameRoute: api/v1/artist
    url: http://localhost:4000
  - nameRoute: api/v1/posts
    url: http://localhost:5000
  - nameRoute: api/v1/comments
    url: http://localhost:5000
  